# DBの設定ファイル

# ファイル名「application.properties」から「.yml」に変更する
# ymlファイルは階層的に記述できるからオススメのファイル形式

# http://localhost:8080/h2-console/ 
# 上記URLでブラウザからアクセス可能
spring:
  datasource:
    # mem メモリのこと 起動ごとに初期化される
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    # デフォルトのname,password
    username: sa
    password:
  # ブラウザでh2dbを確認できる
  h2.console.enabled: true
